events {}

http {

    upstream frontend {
        server frontend:80;
    }

    upstream backend {
        server backend:5000;
    }

    upstream lamp {
        server lamp:80;
    }

    server {

        listen 80;

        location / {
            proxy_pass http://frontend/;
            proxy_set_header Host $host;
        }

        location /api/ {
            proxy_pass http://backend/;
        }

        location /legacy/ {
            proxy_pass http://lamp/;
        }

    }

}